### ISSUE TITLE
Payload length is limited to 253

### ISSUE THREAD

**Issue by iSorp** [dronefleet/mavlink#36]
When serializing (ReflectionPayloadSerializer) an FILE_TRANSFER_PROTOCOL message the exception "IllegalStateException: payload length > 253 for messageio.dronefleet.mavlink.common.FileTransferProtocol" is thrown but the FILE_TRANSFER_PROTOCOL has a length of 254. Shouldn't have a payload a maximum length of 255 bytes?

**Comment by benbarkay** [comment]
Seeing as I can't recall why this limit is there in the first place, I think you're right. Unfortunately it might take me a little while (a week or two) to make a release with a fix for this.

**Comment by aarongnielsen** [comment]
Hi Ben,
I suspect the error here was actually in the MAVLink developer documentation.
According to [this issue](https://github.com/mavlink/mavlink-devguide/issues/91), the documentation used to include the target system ID and target component ID as separate fields from the payload. This is incorrect: it depends on each message type whether these two IDs are included, and if they are, they appear wherever the serialiser puts them, based on the lengths of other fields. The correction is discussed [here](https://github.com/mavlink/mavlink-devguide/pull/100).
The fix for the Dronefleet library appears to be as simple as changing the constant in the serialiser from 253 bytes to 255. I can't see any other reason for the 253-byte limit either. In my own testing, I changed the annotation of the FileTransferProtocol.payload() method to limit the field from 251 bytes to 250, and this was enough to get a file transfer to work with a PX4 SITL.
Hope that helps. :)
Cheers,
Aaron
